application: gombi-grhungary
version: 1
runtime: go
api_version: go1

handlers:
- url: /static/
  static_dir: static
- url: /client/
  static_dir: client
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^client/static/pubspec\..+
- ^client/static/main\.dart\.js\..+
